platform :ios, '10.0'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
#install! 'cocoapods', :deterministic_uuids => false
inhibit_all_warnings!
use_frameworks!

def import_pods
    pod 'XYDWKZombie', :path => '../'
end

target 'Example iOS' do
	platform :ios, '10.0'
	import_pods
end

target 'Example OSX' do
	platform :osx, '14.2'
	import_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
      end
  end
end
